package entities;
// Generated Sep 28, 2016 2:04:10 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;

/**
 * Author generated by hbm2java
 */
public class Author implements java.io.Serializable {

    private Integer authorid;
    
    @Column(name = "name",unique=true)
    private String name;
    private Set books = new HashSet(0);

    public Author() {
    }

    public Author(String name) {
        this.name = name;
    }

    public Author(String name, Set books) {
        this.name = name;
        this.books = books;
    }

    public Integer getAuthorid() {
        return this.authorid;
    }

    public void setAuthorid(Integer authorid) {
        this.authorid = authorid;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Set getBooks() {
        return this.books;
    }

    public void setBooks(Set books) {
        this.books = books;
    }

    @Override
    public String toString() {
        return "ID: " + authorid + " - Name: " + name;
    }

}
