package entities;
// Generated Sep 28, 2016 2:04:10 PM by Hibernate Tools 4.3.1



/**
 * Bookdetail generated by hbm2java
 */
public class Bookdetail  implements java.io.Serializable {


     private Integer isbm;
     //the hinh quan he one to one
     private Book book;
     private Integer numpage;
     private String publisher;

    public Bookdetail() {
    }

	
    public Bookdetail(Book book) {
        this.book = book;
    }
    public Bookdetail(Book book, Integer numpage, String publisher) {
       this.book = book;
       this.numpage = numpage;
       this.publisher = publisher;
    }
   
    public Integer getIsbm() {
        return this.isbm;
    }
    
    public void setIsbm(Integer isbm) {
        this.isbm = isbm;
    }
    public Book getBook() {
        return this.book;
    }
    
    public void setBook(Book book) {
        this.book = book;
    }
    public Integer getNumpage() {
        return this.numpage;
    }
    
    public void setNumpage(Integer numpage) {
        this.numpage = numpage;
    }
    public String getPublisher() {
        return this.publisher;
    }
    
    public void setPublisher(String publisher) {
        this.publisher = publisher;
    }




}


