package entities;
// Generated Sep 28, 2016 2:04:10 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.OneToMany;

/**
 * Category generated by hbm2java
 */
public class Category implements java.io.Serializable {

    private Integer categoryid;
    private String name;

    private Set books = new HashSet(0);

    public Category() {
    }

    public Category(String name) {
        this.name = name;
    }

    public Category(String name, Set books) {
        this.name = name;
        this.books = books;
    }

    public Integer getCategoryid() {
        return this.categoryid;
    }

    public void setCategoryid(Integer categoryid) {
        this.categoryid = categoryid;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Set getBooks() {
        return this.books;
    }

    public void setBooks(Set books) {
        this.books = books;
    }

    @Override
    public String toString() {
        return "ID: " + categoryid + " - Name: " + name;
    }

}
